Added support for LaTeX math in notes
FluffyLabs/graypaper-reader pull request #122
Opened 2024-11-15 14:28 UTC by skoszuta

- LaTeX math can now be used in notes
- Removed some redundant code

2024-11-15 16:20 UTC, tomusdrw requested changes
Can you show how to use it? I've tried on the deployed version:
1. Pasted `c = \\pm\\sqrt{a^2 + b^2}` into the note
2. Clicked "Add"
3. And it just rendered the text as-is.

2024-11-15 16:20 UTC, tomusdrw commented on src/components/NoteManager/Note.tsx
> +          }, 0);
Can we just display an error state (red border) and prevent bluring the note?

2024-11-15 16:20 UTC, tomusdrw commented on src/components/NoteManager/Note.tsx
>          onEditNote(note, noteDirty);
Seems that we are going to save the incorrect note anyway?
So IMHO:
1. Either we disallow incorrect Tex, i.e. we don't save the note
2. Or we accept incorrect tex and just fall back to rendering regular text as-is if the Tex is not valid.

2024-11-15 16:20 UTC, tomusdrw commented on src/components/NoteManager/NoteManager.tsx
> +      alert(`LaTeX validation failed: ${texValidationError}`);
no alerts pls. Same logic as above - either we should disable `add` button if the tex is incorrect or we should save the note anyway and just don't display tex at all.

2024-11-15 16:20 UTC, tomusdrw commented on src/components/TeX/TeX.tsx
> +    if (rootElem && typeof children === "string") {
If `children` has to be a string, maybe just pass a regular prop instead? This is very misleading, any more complex child will cause this code to render nothing.

2024-11-15 16:20 UTC, tomusdrw commented on src/components/TeX/TeX.tsx
> +      rootElem.replaceChildren(renderElem);
Why can't we just use it like that:
```typescript
const ref = useRef();

useEffect(() => {
   renderMathInElement(ref.current, ...);
}, [textToRenderFromProps]);

return (
  <div ref={ref}>
   {textToRenderFromProps}
  </div>
);

2024-11-15 16:20 UTC, tomusdrw commented on src/utils/deserializeLocation.ts
> +export function deserializeLocation(h: string): LocationDetails | null {
```suggestion
export function deserializeLegacyLocation(h: string): LocationDetails | null {
```

2024-11-15 16:20 UTC, tomusdrw commented on src/utils/validateTeX.ts
> +  let errorMsg: null | string = null;
Couldn't we just render to a string?
https://katex.org/docs/api#server-side-rendering-or-rendering-to-a-string

2024-11-15 19:28 UTC, skoszuta commented
> Can you show how to use it? I've tried on the deployed version:
> 
> 1. Pasted `c = \pm\sqrt{a^2 + b^2}` into the note
> 2. Clicked "Add"
> 3. And it just rendered the text as-is.

If I understand correctly we are supposed to allow mixing text and LaTeX? That's only possible if we use delimiters for math content. And here standard delimiters are applied:

```
[
  {left: "$$", right: "$$", display: true},
  {left: "\\(", right: "\\)", display: false},
  {left: "\\begin{equation}", right: "\\end{equation}", display: true},
  {left: "\\begin{align}", right: "\\end{align}", display: true},
  {left: "\\begin{alignat}", right: "\\end{alignat}", display: true},
  {left: "\\begin{gather}", right: "\\end{gather}", display: true},
  {left: "\\begin{CD}", right: "\\end{CD}", display: true},
  {left: "\\[", right: "\\]", display: true}
]
```

2024-11-15 19:31 UTC, skoszuta commented on src/components/NoteManager/Note.tsx
> +          }, 0);
Yeah we can. I still think we should show the error message to the user, because in this case it's particularly useful.

2024-11-15 19:32 UTC, skoszuta commented on src/components/NoteManager/Note.tsx
>          onEditNote(note, noteDirty);
no we aren't. there's a return inside the if.

2024-11-15 19:34 UTC, skoszuta commented on src/components/TeX/TeX.tsx
> +    if (rootElem && typeof children === "string") {
True, this needs to be handled better. I'll work on it on monday.

2024-11-15 19:37 UTC, skoszuta commented on src/components/TeX/TeX.tsx
> +      rootElem.replaceChildren(renderElem);
Because you'd be competing with React by rendering inside a div where React is already rendering text. Not saying this wouldn't work but it's definitely unsafe.

2024-11-15 19:43 UTC, skoszuta commented on src/components/NoteManager/NoteManager.tsx
> +      alert(`LaTeX validation failed: ${texValidationError}`);
im not a fan of alerts either but since weve no solution for displaying validation messages i thought itd save us some time. weve done this before in this codebase ;) nevertheless ill come up with something better

2024-11-15 19:48 UTC, skoszuta commented on src/utils/validateTeX.ts
> +  let errorMsg: null | string = null;
No, katex doesn't work for mixed text and math. To make that work im using an officially supported katex extension: https://katex.org/docs/autorender which only renders to an element. Obviously i was looking for an easier solution but this solves many more problems than it creates.

2024-11-16 06:48 UTC, tomusdrw commented
> > Can you show how to use it? I've tried on the deployed version:
> > 
> > 1. Pasted `c = \pm\sqrt{a^2 + b^2}` into the note
> > 2. Clicked "Add"
> > 3. And it just rendered the text as-is.
> 
> If I understand correctly we are supposed to allow mixing text and LaTeX? That's only possible if we use delimiters for math content. And here standard delimiters are applied:
> 
> ```
> [
>   {left: "$$", right: "$$", display: true},
>   {left: "\\(", right: "\\)", display: false},
>   {left: "\\begin{equation}", right: "\\end{equation}", display: true},
>   {left: "\\begin{align}", right: "\\end{align}", display: true},
>   {left: "\\begin{alignat}", right: "\\end{alignat}", display: true},
>   {left: "\\begin{gather}", right: "\\end{gather}", display: true},
>   {left: "\\begin{CD}", right: "\\end{CD}", display: true},
>   {left: "\\[", right: "\\]", display: true}
> ]
> ```
> 
> Try the following for a simple example
> 
> ```
> \[ x^n + y^n = z^n \]
> ```

Can we add:
```
{left: "$", right: "$", display: false},
```
I was trying that because afair it's a standard inline-math in Latex and it didn't work. Also it would be good to display an example somewhere (maybe even in the placeholder would be enough).

2024-11-18 09:31 UTC, skoszuta commented on src/components/TeX/TeX.tsx
> +      rootElem.replaceChildren(renderElem);
It is different in that i'm not replacing any children that React put there. As far as React is concerned it's an empty div.

2024-11-18 09:36 UTC, skoszuta commented on src/utils/validateTeX.ts
> +  let errorMsg: null | string = null;
katex's auto-render is more than 200 lines of code. I figured this is less terrible than copying that entire thing over to our codebase or writing it from scratch. let me know if you have a preference or other ideas.

2024-11-18 09:41 UTC, skoszuta commented
> > > Can you show how to use it? I've tried on the deployed version:
> > > 
> > > 1. Pasted `c = \pm\sqrt{a^2 + b^2}` into the note
> > > 2. Clicked "Add"
> > > 3. And it just rendered the text as-is.
> > 
> > 
> > If I understand correctly we are supposed to allow mixing text and LaTeX? That's only possible if we use delimiters for math content. And here standard delimiters are applied:
> > ```
> > [
> >   {left: "$$", right: "$$", display: true},
> >   {left: "\\(", right: "\\)", display: false},
> >   {left: "\\begin{equation}", right: "\\end{equation}", display: true},
> >   {left: "\\begin{align}", right: "\\end{align}", display: true},
> >   {left: "\\begin{alignat}", right: "\\end{alignat}", display: true},
> >   {left: "\\begin{gather}", right: "\\end{gather}", display: true},
> >   {left: "\\begin{CD}", right: "\\end{CD}", display: true},
> >   {left: "\\[", right: "\\]", display: true}
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Try the following for a simple example
> > ```
> > \[ x^n + y^n = z^n \]
> > ```
> 
> Can we add:
> 
> ```
> {left: "$", right: "$", display: false},
> ```
> 
> I was trying that because afair it's a standard inline-math in Latex and it didn't work. Also it would be good to display an example somewhere (maybe even in the placeholder would be enough).

Sure, we can add $...$

2024-11-18 09:57 UTC, tomusdrw commented on src/utils/validateTeX.ts
> +  let errorMsg: null | string = null;
`auto-render` is fine, what I'm thinking is using it to implement `renderToString` like so:
```typescript
export function renderLatexToString(str: string): null | string {
  const renderElem = document.createElement("span");
  renderElem.appendChild(document.createTextNode(str));

  let errorMsg: null | string = null;
  renderMathInElement(renderElem, {
    errorCallback: (_msg, err) => {
      reject(err.message);
    },
  });

  return errorMsg
      ? { error: errorMsg }
      : { string: renderElement.innerHTML }; 
}
```

The same function can be then used for validation and rendering using `dangerouslySetInnerHTML`. We can even avoid rendering the formula twice (since we just attach the rendered string to the note after it's validated).

But I'm not going to die on that hill, I feel like you are a bit reluctant to change the code and I can live with it as-is, so up to you to change it.
I am just leaving my suggestion which IMHO has cleaner boundaries between manual DOM manipulation and React.

2024-11-18 10:00 UTC, tomusdrw commented on src/components/TeX/TeX.tsx
> +      rootElem.replaceChildren(renderElem);
> As far as React is concerned it's an empty div.

Then AFAIK any content from that div will be removed when the component is re-rendered, hence my comments here that I don't see much difference.
Anyway, I feel the cleanest approach would be to have `renderToString` and use `setInnerHTML` as suggested in other comment.

2024-11-18 10:07 UTC, skoszuta commented on src/utils/validateTeX.ts
> +  let errorMsg: null | string = null;
Doing it this way sounds good. I just thought you dont like the "render to an element" part in general.

2024-11-20 10:05 UTC, skoszuta commented on src/utils/renderMathToString.ts
> +    },
It doesn't throw. Auto-render catches the error and always calls the error callback (which has a default value of `console.error`)

2024-11-20 14:06 UTC, merged