Migrate selection for link checker
FluffyLabs/graypaper-reader pull request #134
Opened 2024-12-12 09:53 UTC by skoszuta

2024-12-13 12:57 UTC, skoszuta commented on tools/links-check/report.ts
> +      console.info(`  ⚠️  ${link.url}`);
Oki, restoring the dino. However note that from now on im showing links that link to existing blocks but failed migration as (most likely) broken.

2024-12-15 11:05 UTC, tomusdrw requested changes

2024-12-15 11:05 UTC, tomusdrw commented on tools/links-check/index.ts
> +
Please extract support for CLI parameter `--ignore-file` (that would be parsed by `ignore` package), but is not expected to automatically find `.gitignore` files to a separate PR.

While it's a single CLI parameter, there is for sure going to be more, so we should think about better (more generic) way to extract these parameters from `args`.

2024-12-15 11:05 UTC, tomusdrw commented on tools/links-check/migrate.ts
> +  });
Please move to a separate PR. The user should not be prompted for anything, we should rather provide a CLI flag to auto-overwrite the files. The tool is meant to be running in a non-interactive environment, just like linters, so on CI we can check that links are valid, and locally we can migrate the hooks by running a special command.

2024-12-16 12:42 UTC, skoszuta commented on tools/links-check/index.ts
> +}
all fair points. i did add a message to the output saying that we're using a gitignore file and which one but that doesn't solve other issues.

2024-12-16 13:05 UTC, skoszuta commented on tools/links-check/migrate.ts
> +  });
removed, will appear in a separate PR

2024-12-16 13:21 UTC, tomusdrw approved these changes

2024-12-16 13:22 UTC, merged