Load remote notes. Display & filter by labels.
FluffyLabs/graypaper-reader pull request #138
Opened 2024-12-20 16:07 UTC by tomusdrw

This PR reworks a bit the internal model for storing notes. It's required to support features outlined in #83 

1. On top of that I've implemented displaying and filtering by labels (no user-defined labels yet).
2. Importing notes is not overwritting the existing ones (Closes #76)
3. Editing the node is re-worked (no more `onBlur`)
4. We have the ability to load remote notes from URL (see `remoteNotesSources`; no UI to edit it yet)

I don't want to add much more to this PR to make it easier to review. So far the changes should mostly only affect how notes are displayed. The only new feature visible at once is filtering by labels (but the user will only see one label: "local").

2024-12-23 13:20 UTC, skoszuta requested changes
Generally looks good. There are couple of things I'd like to point out though:
- It feels messy to save notes along with data that can be inferred in runtime, such as:
  - local/remote/imported labels (unless you'd drop the source property)
  - canMigrateTo: this one especially since it serves no purpose at all in local storage
- I feel like we should introduce note spec versioning. its a reasonable moment to do so because we can treat all notes without a spec property as v2. if we dont do this now were in for quite a mess on next iterations.

The rest is in the comments. Cheers

2024-12-23 13:20 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +    saveToLocalStorage(localNotes);
please remove unnecessary data, such as `canMigrateTo` or `local/remote/imported` labels, before saving to local storage.

2024-12-23 23:01 UTC, tomusdrw reviewed
All points are pretty valid and should now be addressed.

Decided to change the note data model a bit. Cleaned it up from unnecessary stuff:
1. `pageNumber` was duplicated in `selectionStart`
2. `selectionString` was not really used and can be better deducted from the blocks (we don't need it as a safety measure any more imho).
3. Introduced an explicit container for notes (instead of storing just an array), since it avoid possible inconsistency in notes inside the array (what if I have a bunch of V2 and V3 notes mixed together in one array?) and I'm pretty sure it might come handy in the future when we need to attach more data there.

2024-12-27 16:00 UTC, skoszuta requested changes
I agree with the goals you're going after but:
- import/export is broken
- some parts seem unfinished/untested/unclear
Details in the comments

As a general side note the code seems a little convoluted for what it does and NotesProvider grew kinda large. That's not a blocker but just my impression.

Cheers

2024-12-27 16:00 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +          newNotes = parseNotesFromJson(jsonStr, `${LABEL_IMPORTED}${label}`).notes;
If i understand correctly, imported v3 notes will never receive the "Imported" label

2024-12-27 16:00 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +  Imported = 1,
`NoteSource.Imported` is never used anywhere

2024-12-27 16:00 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +      throw new Error("Notes JSON should be an array.");
This `throw` breaks v2 imports

2024-12-27 16:00 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +      const strNotes = JSON.stringify(localNotes);
You export the `localNotes` array without the wrapper therefore they're always treated as V2 when importing.

2024-12-27 16:00 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +            return {
this is the exact same return as in line 394. Please merge them

2024-12-27 16:00 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +          const hash = await xxhash32(`${source}-${note.version}-${note.date}-${note.content}`);
i do believe the hash lib is an overkill since you can simply use that string (or any simple hash doable in js) as key for react components. up to you though, its fun to have nice hashes

2024-12-27 16:00 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +export type INote = ISelectionParams & {
The naming here is a bit confusing. There's `INoteV2`, `INoteV3` and then `INote` which has an entirely different hierarchy of properties and serves a different purpose. It would be nice to indicate that:
- it's a decorated version of a raw note (you change naming the other way around, by changing INoteV2 or INoteV3 to something else)
- the selection params on this one are migrated/temporary.

2024-12-28 16:23 UTC, tomusdrw commented on src/components/NotesProvider/NotesProvider.tsx
> +          newNotes = parseNotesFromJson(jsonStr, `${LABEL_IMPORTED}${label}`).notes;
Yes.

2024-12-28 16:23 UTC, tomusdrw commented on src/components/NotesProvider/NotesProvider.tsx
> +  Imported = 1,
Removed

2024-12-28 16:23 UTC, tomusdrw commented on src/components/NotesProvider/NotesProvider.tsx
> +      throw new Error("Notes JSON should be an array.");
Fixed.

2024-12-28 16:23 UTC, tomusdrw commented on src/components/NotesProvider/NotesProvider.tsx
> +      const strNotes = JSON.stringify(localNotes);
Fixed.

2024-12-28 16:23 UTC, tomusdrw commented on src/components/NotesProvider/NotesProvider.tsx
> +            return {
Fixed.

2024-12-28 16:23 UTC, tomusdrw commented on src/components/NotesProvider/NotesProvider.tsx
> +          const hash = await xxhash32(`${source}-${note.version}-${note.date}-${note.content}`);
Removed.

2024-12-28 16:23 UTC, tomusdrw commented on src/components/NotesProvider/NotesProvider.tsx
> +export type INote = ISelectionParams & {
Reworked.

2024-12-28 16:25 UTC, tomusdrw commented
Reworked & refactored the code further.

- [ ] Extracted hooks from `NotesProvider`
- [ ] Moved local storage management and import/export functions to utils and added tests.

Let me know wdyt.

2024-12-30 10:02 UTC, skoszuta commented on src/components/NotesProvider/NotesProvider.tsx
> +          remoteNotes.push(...notes);
indeed there isn't a biome rule for it. it looks like the lead maintainer has an opinion on this topic: https://github.com/biomejs/biome/discussions/3#discussioncomment-7379356

2024-12-30 11:16 UTC, skoszuta approved these changes
Looking good! Nice call with adding the tests.

One thing i noticed is that when a note fails automatic migration we show it to the user without an ability to migrate it manually. If that wasn't intentional that's the only thing I'd consider fixing.

Other than that lgtm 🚀

2025-01-01 22:38 UTC, tomusdrw commented
> Looking good! Nice call with adding the tests.
> 
> One thing i noticed is that when a note fails automatic migration we show it to the user without an ability to migrate it manually. If that wasn't intentional that's the only thing I'd consider fixing.
> 
> Other than that lgtm 🚀

Good catch, fixed, thanks!

2025-01-01 22:38 UTC, merged